# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test6.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 1024)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 390, 341, 554))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton::indicator {\n"
"    width: 80px;\n"
"    height: 80px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:hover {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:hover {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton::indicator {\n"
"    width: 80px;\n"
"    height: 80px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:hover {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:hover {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("QRadioButton::indicator {\n"
"    width: 80px;\n"
"    height: 80px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:hover {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:hover {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("QRadioButton::indicator {\n"
"    width: 80px;\n"
"    height: 80px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:hover {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-off.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:hover {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked:pressed {\n"
"    image: url(/home/eo/images/toggle-button-on.png);\n"
"}\n"
"\n"
"")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 120, 171, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../images/baby.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 290, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 601, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"background-color: rgb(0, 162, 232);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color: rgb(0, 162, 232);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 71, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("image: url(/home/eo/images/heater-res.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 180, 100, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    height: 80px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(143, 143, 143);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 180, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("height: 80px;\n"
"width: 80px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 260, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-down.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-down-psv.png);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 100, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-up.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-up-psv.png);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 180, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("height: 80px;\n"
"width: 80px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 100, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-up.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-up-psv.png);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 260, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-down.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    height: 80px;\n"
"    width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    image: url(/home/eo/images/swipe-down-psv.png);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 70, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_2.setText(_translate("MainWindow", "Lamp 1"))
        self.radioButton_3.setText(_translate("MainWindow", "Lamp 2"))
        self.radioButton_4.setText(_translate("MainWindow", "Buzzer"))
        self.radioButton_5.setText(_translate("MainWindow", "Alarm Led"))
        self.label_2.setText(_translate("MainWindow", "--.--"))
        self.pushButton_3.setText(_translate("MainWindow", "Prewarm"))
        self.label_5.setText(_translate("MainWindow", "%25"))
        self.label_7.setText(_translate("MainWindow", "36"))
        self.label_8.setText(_translate("MainWindow", "SET (°C)"))
